/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    'debugbar.openhandler': [];
    'debugbar.clockwork': [
      {
        name: 'id';
        required: true;
      },
    ];
    'debugbar.assets.css': [];
    'debugbar.assets.js': [];
    'debugbar.cache.delete': [
      {
        name: 'key';
        required: true;
      },
      {
        name: 'tags';
        required: false;
      },
    ];
    login: [];
    logout: [];
    'password.request': [];
    'password.reset': [
      {
        name: 'token';
        required: true;
      },
    ];
    'password.email': [];
    'password.update': [];
    register: [];
    'verification.notice': [];
    'verification.verify': [
      {
        name: 'id';
        required: true;
      },
      {
        name: 'hash';
        required: true;
      },
    ];
    'verification.send': [];
    'user-profile-information.update': [];
    'user-password.update': [];
    'password.confirmation': [];
    'password.confirm': [];
    'two-factor.login': [];
    'two-factor.enable': [];
    'two-factor.confirm': [];
    'two-factor.disable': [];
    'two-factor.qr-code': [];
    'two-factor.secret-key': [];
    'two-factor.recovery-codes': [];
    'profile.show': [];
    'other-browser-sessions.destroy': [];
    'current-user-photo.destroy': [];
    'current-user.destroy': [];
    'ignition.healthCheck': [];
    'ignition.executeSolution': [];
    'ignition.updateConfig': [];
    dashboard: [];
    'posts.create': [];
    'posts.store': [];
    'posts.comments.store': [
      {
        name: 'post';
        required: true;
        binding: 'id';
      },
    ];
    'comments.update': [
      {
        name: 'comment';
        required: true;
        binding: 'id';
      },
    ];
    'comments.destroy': [
      {
        name: 'comment';
        required: true;
        binding: 'id';
      },
    ];
    'posts.index': [
      {
        name: 'topic';
        required: false;
        binding: 'slug';
      },
    ];
    'posts.show': [
      {
        name: 'post';
        required: true;
        binding: 'id';
      },
      {
        name: 'slug';
        required: true;
      },
    ];
  }
}
export {};
